"""update the products table (amount)

Revision ID: e302132bf339
Revises: e85afdac2e7c
Create Date: 2026-04-13 09:53:03.798453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e302132bf339'
down_revision = 'e85afdac2e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.drop_column('Amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Amount', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
